permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

filter: 'category'

# 作者信息
author: 
  name: CRI
  email: ecpkn_cri@yeah.net
  github: https://github.com/sino-crdc

# 站点信息
title: cri.io
description: Le Centre de Recherche et d'Innovation
url: sino-crdc.github.io/cri.io
email: ecpkn_cri@yeah.net
github: sino-crdc
# rss_url: /pages/atom.xml

# Social account
# twitter:  username
#weibo:    JavcMak
github:   sino-crdc
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico

sass:
  style: compressed
gems:
  - jekyll-sitemap
